name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Generate Snake GIF and SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: irisxvii  # Your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 3: Debug: List files in dist directory to ensure they were generated
      - name: List files in dist directory
        run: ls -la dist  # Check which files are created

      # Step 4: Run git status to see changes
      - run: git status

      # Step 5: Push changes to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Step 6: Deploy to Output branch (GitHub Pages)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
